# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'add.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(672, 413)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(130, 30, 351, 71))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.employee_name_input = QtWidgets.QLineEdit(Dialog)
        self.employee_name_input.setGeometry(QtCore.QRect(240, 120, 281, 22))
        self.employee_name_input.setObjectName("employee_name_input")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(130, 120, 91, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(140, 160, 91, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.employee_position_input = QtWidgets.QLineEdit(Dialog)
        self.employee_position_input.setGeometry(QtCore.QRect(240, 160, 281, 22))
        self.employee_position_input.setObjectName("employee_position_input")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(110, 200, 121, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.employee_rate_input = QtWidgets.QLineEdit(Dialog)
        self.employee_rate_input.setGeometry(QtCore.QRect(240, 200, 281, 22))
        self.employee_rate_input.setObjectName("employee_rate_input")
        self.save_employee_btn = QtWidgets.QPushButton(Dialog)
        self.save_employee_btn.setGeometry(QtCore.QRect(130, 250, 151, 28))
        self.save_employee_btn.setObjectName("save_employee_btn")
        self.cancel_btn = QtWidgets.QPushButton(Dialog)
        self.cancel_btn.setGeometry(QtCore.QRect(390, 250, 151, 28))
        self.cancel_btn.setObjectName("cancel_btn")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

     # ✅ DAPAT NASA LOOB NG CLASS
    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate

        Dialog.setWindowTitle(_translate("Dialog", "Add Employee"))
        self.label.setText(_translate("Dialog", "ADD EMPLOYEE"))

        self.label_2.setText(_translate("Dialog", "Name"))
        self.label_3.setText(_translate("Dialog", "Position"))
        self.label_4.setText(_translate("Dialog", "Salary"))

        self.save_employee_btn.setText(_translate("Dialog", "SAVE"))
        self.cancel_btn.setText(_translate("Dialog", "CANCEL"))


   