# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'admin.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(623, 591)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(140, 0, 321, 71))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.payroll_records_btn = QtWidgets.QPushButton(Dialog)
        self.payroll_records_btn.setGeometry(QtCore.QRect(190, 450, 231, 28))
        self.payroll_records_btn.setObjectName("payroll_records_btn")
        self.add_employee_btn = QtWidgets.QPushButton(Dialog)
        self.add_employee_btn.setGeometry(QtCore.QRect(190, 160, 231, 28))
        self.add_employee_btn.setObjectName("add_employee_btn")
        self.view_employee_btn = QtWidgets.QPushButton(Dialog)
        self.view_employee_btn.setGeometry(QtCore.QRect(190, 210, 231, 28))
        self.view_employee_btn.setObjectName("view_employee_btn")
        self.attendance_btn = QtWidgets.QPushButton(Dialog)
        self.attendance_btn.setGeometry(QtCore.QRect(190, 300, 231, 28))
        self.attendance_btn.setObjectName("attendance_btn")
        self.calculate_payroll_btn = QtWidgets.QPushButton(Dialog)
        self.calculate_payroll_btn.setGeometry(QtCore.QRect(190, 400, 231, 28))
        self.calculate_payroll_btn.setObjectName("calculate_payroll_btn")
        self.employee_label = QtWidgets.QLabel(Dialog)
        self.employee_label.setGeometry(QtCore.QRect(10, 100, 231, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.employee_label.setFont(font)
        self.employee_label.setObjectName("employee_label")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(10, 250, 131, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(10, 350, 131, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(10, 490, 131, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.logout_btn = QtWidgets.QPushButton(Dialog)
        self.logout_btn.setGeometry(QtCore.QRect(190, 540, 231, 28))
        self.logout_btn.setObjectName("logout_btn")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "ADMIN DASHBOARD"))
        self.payroll_records_btn.setText(_translate("Dialog", "PAYROLL RECORDS"))
        self.add_employee_btn.setText(_translate("Dialog", "ADD EMPLOYEES"))
        self.view_employee_btn.setText(_translate("Dialog", "VIEW EMPLOYEES"))
        self.attendance_btn.setText(_translate("Dialog", "RECORD ATTENDANCE"))
        self.calculate_payroll_btn.setText(_translate("Dialog", "CALCULATE PAYROLL"))
        self.employee_label.setText(_translate("Dialog", "EMPLOYEE MANAGEMENT:"))
        self.label_3.setText(_translate("Dialog", "ATTENDANCE:"))
        self.label_4.setText(_translate("Dialog", "PAYROLL:"))
        self.label_5.setText(_translate("Dialog", "SYSTEM:"))
        self.logout_btn.setText(_translate("Dialog", "LOGOUT"))