# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'records.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(920, 528)
        self.payroll_table = QtWidgets.QTableWidget(Dialog)
        self.payroll_table.setGeometry(QtCore.QRect(50, 140, 771, 211))
        self.payroll_table.setObjectName("payroll_table")
        self.payroll_table.setColumnCount(6)
        self.payroll_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.payroll_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.payroll_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.payroll_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.payroll_table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.payroll_table.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.payroll_table.setHorizontalHeaderItem(5, item)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(310, 0, 331, 71))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.search_input = QtWidgets.QLineEdit(Dialog)
        self.search_input.setGeometry(QtCore.QRect(280, 80, 231, 22))
        self.search_input.setObjectName("search_input")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(110, 80, 161, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(530, 80, 93, 28))
        self.pushButton.setObjectName("pushButton")
        self.refresh_btn = QtWidgets.QPushButton(Dialog)
        self.refresh_btn.setGeometry(QtCore.QRect(120, 400, 161, 31))
        self.refresh_btn.setObjectName("refresh_btn")
        self.delete_btn = QtWidgets.QPushButton(Dialog)
        self.delete_btn.setGeometry(QtCore.QRect(350, 400, 161, 31))
        self.delete_btn.setObjectName("delete_btn")
        self.back_btn = QtWidgets.QPushButton(Dialog)
        self.back_btn.setGeometry(QtCore.QRect(580, 400, 161, 31))
        self.back_btn.setObjectName("back_btn")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        item = self.payroll_table.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "NAME"))
        item = self.payroll_table.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "DATE"))
        item = self.payroll_table.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "HOURS"))
        item = self.payroll_table.horizontalHeaderItem(3)
        item.setText(_translate("Dialog", "RATE"))
        item = self.payroll_table.horizontalHeaderItem(4)
        item.setText(_translate("Dialog", "GROSS"))
        item = self.payroll_table.horizontalHeaderItem(5)
        item.setText(_translate("Dialog", "NET"))
        self.label.setText(_translate("Dialog", "PAYROLL RECORDS"))
        self.label_2.setText(_translate("Dialog", "SEARCH EMPLOYEE:"))
        self.pushButton.setText(_translate("Dialog", "search_btn"))
        self.refresh_btn.setText(_translate("Dialog", "REFRESH"))
        self.delete_btn.setText(_translate("Dialog", "DELETE"))
        self.back_btn.setText(_translate("Dialog", "BACK"))

import sqlite3
from PyQt5 import uic
from PyQt5.QtWidgets import QDialog, QTableWidgetItem


class PayrollRecordsWindow(QDialog):
    def __init__(self):
        super().__init__()
        uic.loadUi("records.ui", self)

        self.refresh_btn.clicked.connect(self.load_payroll)
        self.delete_btn.clicked.connect(self.delete_record)
        self.back_btn.clicked.connect(self.close)

        self.load_payroll()

    # LOAD PAYROLL
    def load_payroll(self):
        conn = sqlite3.connect("payroll.db")
        cursor = conn.cursor()

        cursor.execute("""
        SELECT employees.fullname,
               payroll.date,
               payroll.hours,
               payroll.rate,
               payroll.gross,
               payroll.net
        FROM payroll
        JOIN employees
        ON payroll.employee_id = employees.id
        """)

        records = cursor.fetchall()

        self.payroll_table.setRowCount(0)

        for row_number, row_data in enumerate(records):
            self.payroll_table.insertRow(row_number)

            for column_number, data in enumerate(row_data):
                self.payroll_table.setItem(
                    row_number,
                    column_number,
                    QTableWidgetItem(str(data))
                )

        conn.close()

    # DELETE RECORD
    def delete_record(self):

        row = self.payroll_table.currentRow()

        if row < 0:
            return

        name = self.payroll_table.item(row, 0).text()
        date = self.payroll_table.item(row, 1).text()

        conn = sqlite3.connect("payroll.db")
        cursor = conn.cursor()

        cursor.execute("""
        DELETE FROM payroll
        WHERE employee_id = (
            SELECT id FROM employees WHERE fullname=?
        )
        AND date=?
        """, (name, date))

        conn.commit()
        conn.close()

        self.load_payroll()