# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'signup.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(656, 454)
        self.signup_title_label = QtWidgets.QLabel(Dialog)
        self.signup_title_label.setGeometry(QtCore.QRect(200, 20, 321, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.signup_title_label.setFont(font)
        self.signup_title_label.setStyleSheet("color: #2c3e50;")
        self.signup_title_label.setObjectName("signup_title_label")
        self.username_label = QtWidgets.QLabel(Dialog)
        self.username_label.setGeometry(QtCore.QRect(180, 80, 121, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.username_label.setFont(font)
        self.username_label.setObjectName("username_label")
        self.password_label = QtWidgets.QLabel(Dialog)
        self.password_label.setGeometry(QtCore.QRect(180, 180, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.password_label.setFont(font)
        self.password_label.setObjectName("password_label")
        self.signup_username = QtWidgets.QLineEdit(Dialog)
        self.signup_username.setGeometry(QtCore.QRect(180, 120, 281, 41))
        self.signup_username.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.signup_username.setObjectName("signup_username")
        self.signup_password = QtWidgets.QLineEdit(Dialog)
        self.signup_password.setGeometry(QtCore.QRect(180, 220, 281, 41))
        self.signup_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.signup_password.setObjectName("signup_password")
        self.register_btn = QtWidgets.QPushButton(Dialog)
        self.register_btn.setGeometry(QtCore.QRect(180, 360, 93, 28))
        self.register_btn.setStyleSheet("background-color: #3498db;\n"
"color: white;\n"
"border-radius: 5px;")
        self.register_btn.setObjectName("register_btn")
        self.back_btn = QtWidgets.QPushButton(Dialog)
        self.back_btn.setGeometry(QtCore.QRect(370, 360, 93, 28))
        self.back_btn.setStyleSheet("background-color: #95a5a6;\n"
"color: white;\n"
"border-radius: 5px;")
        self.back_btn.setObjectName("back_btn")
        self.Confirm = QtWidgets.QLabel(Dialog)
        self.Confirm.setGeometry(QtCore.QRect(180, 260, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Confirm.setFont(font)
        self.Confirm.setObjectName("Confirm")
        self.signup_confirm = QtWidgets.QLineEdit(Dialog)
        self.signup_confirm.setGeometry(QtCore.QRect(180, 300, 281, 41))
        self.signup_confirm.setEchoMode(QtWidgets.QLineEdit.Password)
        self.signup_confirm.setObjectName("signup_confirm")
        self.message_label = QtWidgets.QLabel(Dialog)
        self.message_label.setGeometry(QtCore.QRect(140, 400, 361, 31))
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        font.setPointSize(18)
        self.message_label.setFont(font)
        self.message_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.message_label.setObjectName("message_label")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.signup_title_label.setText(_translate("Dialog", "CREATE ACCOUNT"))
        self.username_label.setText(_translate("Dialog", "<html><head/><body><p>Username :</p></body></html>"))
        self.password_label.setText(_translate("Dialog", "<html><head/><body><p>Password :</p></body></html>"))
        self.signup_username.setPlaceholderText(_translate("Dialog", "Enter Username "))
        self.signup_password.setPlaceholderText(_translate("Dialog", "Enter Password"))
        self.register_btn.setText(_translate("Dialog", "Register"))
        self.back_btn.setText(_translate("Dialog", "Back"))
        self.Confirm.setText(_translate("Dialog", "Confirm Password :"))
        self.signup_confirm.setPlaceholderText(_translate("Dialog", "Confirm Password"))
        self.message_label.setText(_translate("Dialog", " "))